import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import Navbar from "@/app/components/navbar";
import "./globals.css";

const space_grotesk = Space_Grotesk({
  variable: "--font-space_grotesk",
  weight: ["300", "400", "500", "600", "700", ],
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${space_grotesk.variable} antialiased max-w-6xl mx-auto`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
